### ISSUE TITLE
install of release 12 causes files to be no longer listed in HOME directory

### ISSUE THREAD

**Issue by james-cook** [newroco/emlviewer#13]
Related to https://github.com/newroco/emlviewer/issues/12#issuecomment-628680594
I installed release 12 (instead of 10) on my NC15 installation.
There was a schema change in emlviewer for which I ran occ upgrade...

The weird thing is I can no longer browse files in HOME etc. 
Disabling the app emlviewer does make me able to browse my files again...
Very strange

**Comment by james-cook** [comment]
I upgrades NC15 to NC17 and this no longer seems to happen.
But  display of eml files is "erratic". 
Sometimes clicking on the file leads to a "download" dialog
Sometimes clicking on the file leads to a display of the email

I managed once to click on an eml containing embedded photos - but these were not displayed

**Comment by james-cook** [comment]
I'm switching this to closed as the initial problem has been solved by upgrading NC.
I'll document my experiences with images in another issue

**Comment by lucianpricop** [comment]
> I upgraded NC15 to NC17 and this no longer seems to happen.
> But display of eml files is "erratic".
> Sometimes clicking on the file leads to a "download" dialog
> Sometimes clicking on the file leads to a display of the email
> 
> I managed once to click on an eml containing embedded photos - but these were not displayed

Thank you so much to taking the time to test and upgrade. I was wondering if the erratic behaviour was due to older JS code served from browser cache. So now that emls to render, does it still happen to offer the download option?  Before version 0.0.10 we relied on page load trigger to catch clicks on eml files, so if you clicked before the page loaded you were presented with a download dialog. Now, we're doing it differently, working with NC js  classes and this shouldn't happen, at least I couldn't replicate it anymore.

So, if you were to still have the issue, clicking on a file quickly after a refresh it should give you the download dialog. Please let me know. Thanks
